version: 2.1
jobs:
        build:
                docker:
                        - image:circleci/golang
        steps:
                - checkout
                - run: echo "always runs"
                          
