version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - run: make
      - store_artifacts:
          path: /bin/insider
          destination: incider
