version: 2.1

executors:
  go:
    description: Choose required Go container version for build 
    parameters:
      version:
        description: Select the version to use in executor
        type: string
        default: "1.13"
    docker: 
      - image: cimg/go:<< parameters.version >>

commands:
  make: #You can define on which system type to compile build. For possible combination of params read coresponding Makefile on github 
    parameters:
      platform:
        default: "linux64"
        type: string
      binary:
        default: "insider-linux-amd64"
        type: string
    steps:
      - run: 
          command: make <<parameters.platform>>
      - run: 
          command: mv <<parameters.platform>> /tmp/
      - persist_to_workspace:
          root: /tmp/
          paths: 
            - <<parameters.platform>>

jobs:
  build:
    executor: go
    steps:
      - checkout
      - make
#      - run: 
#          name: Create build
#          command: |
#            make linux64
#            mv insider-linux-amd64 /tmp/
#      - persist_to_workspace:
#          root: /tmp/
#          paths: 
#            - insider-linux-amd64
  deploy:
    executor: go
    steps:
      - attach_workspace:
          at: /tmp/
      - add_ssh_keys:
          fingerprints:
            - "bd:1b:00:1f:aa:ce:17:e3:52:24:fd:67:23:fc:f8:b7"
      - run:
          name: deploy build
          command: scp -o "StrictHostKeyChecking no" /tmp/insider-linux-amd64 ubuntu@ec2-18-224-136-171.us-east-2.compute.amazonaws.com:/opt/insider/
workflows:
  main:
    jobs:
      - build
      - deploy:
          requires:
            - build
