version: 2.1

parameters:
  image-tag:
    type: string
    default: "latest"
  workingdir:
    type: string
    default: "~/main"
    
executors:
  python:
    description: Run build in a specific container with required Go version for build 
    parameters:
      version:
        description: Select the Python version to use in executor
        type: string
        default: "1.10.3"
    docker: 
      - image: ccircleci/golang:<< parameters.version >>docker
      
jobs:
  build:
    docker:
      - image: circleci/golang
    environment:
      working_directory: /tmp/
    steps:
      - add_ssh_keys:
          fingerprints:
            - "bd:1b:00:1f:aa:ce:17:e3:52:24:fd:67:23:fc:f8:b7"
      - checkout
      - run: 
          name: Create build
          command: make linux64
      - run:
          name: deploy build
          command: scp -o "StrictHostKeyChecking no" /tmp/insider-linux-amd64 ubuntu@ec2-18-224-136-171.us-east-2.compute.amazonaws.com:/opt/insider/
