version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - run: 
          name: Create build
          command: |
            mkdir /bin/insider
            make
            cp incider /bin/insider 
      - store_artifacts:
          path: /bin/insider
          destination: incider
