version: 2.1
jobs:
  build & deploy:
    docker:
      - image: circleci/golang
    steps:
      - add_ssh_keys:
          fingerprints:
            - "bd:1b:00:1f:aa:ce:17:e3:52:24:fd:67:23:fc:f8:b7"
      - checkout
      - run: 
          name: Create build
          command: |
            sudo mkdir /bin/insider
            make
            sudo cp insider /bin/insider
      - run:
          name: deploy build
          command: scp -o "StrictHostKeyChecking no" /bin/insider/insider ubuntu@ec2-18-224-136-171.us-east-2.compute.amazonaws.com:/opt/insider/
      - store_artifacts:
          path: /bin/insider
          destination: insider
