jobs:
        build:
                docker:
                        - image:circleci/golang
        steps:
                - checkout
                - run:
                        command: |
                          cd insider
                          make
                          
